### PR TITLE
create TOC plugin

### LINKED ISSUE #1: Generate toc.js automatically from zone folder structure
If you need any help, just holler. @dheniges is likely your man here... This should be a fun task!

### PR DESCRIPTION
**Pull request by care0hlyn**
resolves #1

### CODE REVIEW

**Comment by jcontonio** [comment]
This is great. There are some formatting issues in the output. I've indented it and pasted it here so you can compare with TOC.js and fix. You'll see there are extra container objects. Try getting the output as close to TOC.js as possible and push back. You can test this by just running `jekyll build` and it will auto-run. 

```
/** * Table of Contents for the Mindspace LMS */
window.toc = {
    date: "",
    author: "Mindspace",
    zones: [{
        //szn
        {
            zone_id: "szn",
            label: "some-zone-name",
            levels: [
                //sln
                {
                    level_id: "szn",
                    level_label: "some-level-name",
                    modules: [
                        //smn
                        {
                            module_id: "sln",
                            module_label: "the-first-level",
                            lessons: [
                                "sln_smn_1",
                                "sln_smn_2",
                                "sln_smn_3",
                                "sln_smn_4",
                                "sln_smn_5"
                            ]
                        }
                    ]
                }
            ]
        }
    }]
};
```

**Comment by jcontonio** [comment]
Also, can you test this with multiple zone folders, adding more markdown structure? No need to commit that new stuff.

**Comment by jcontonio** [comment]
Should we delete this PR? There are two PR's for the same feature.

**Comment by care0hlyn** [comment]
closing this

**Pull request closed without merging**
